### ISSUE TITLE
Guest mode

### ISSUE THREAD

**Issue by zoriya** [Chroma-Case/Chromacase#149]
### En tant que

Utilisateur

### Je veux

Pouvoir tester Chromacase sans avoir a creer de compte

### Estimation du temps

6 J/H

### Description

Permettre à l'utilisateur de jouer sans créer de compte, toutes les informations doivent pouvoir être sauvegardé dans le back pour que l'utilisateur puisse sauvegarder sa progression dans un compte si voulu.

### Definition of Done (DoD)

 - [x] Creer une route API pour creer un compte "guest"
 - [x] Rajouter des champs dans le compte pour que le front puisse differencier les comptes "guest" des normeaux et indiquer le nombre de parties restantes.
 - [x] Sauvegarder les comptes guest en base de donee
 - [x] Creer une route pour convertir un compte guest en vrai compet
 - [x] Faire des tests robots.

**Comment by Octopus773** [comment]
Il faudra bien que l'api me donne aussi : le nombre de parties restantes que le compte peut faire et bien signaler d'une facon que le compte est un invité puisqu'on utilisera les mêmes routes api
