### ISSUE TITLE
Découvrir Flutter Web

### ISSUE THREAD

**Issue by Arthi-chaud** [Chroma-Case/Chromacase#24]
### En tant que

Développeur

### Je veux

Avoir des connaissances pour créer une application web en Flutter

### Estimation du temps

5J/H

### Description

Le but est d'apprendre les bases de Flutter web, afin de n'avoir qu'une seule codebase pour le projet final.

L'enjeu est également d'avoir un code qui permet d'avoir une interface responsive avec les différentes tailles d'écran (smartphone, tablette, ordinateur).

Ces pages, bien qu'ayant des données statiques, utiliseront des fonctionnalités du projet final

### Definition of Done (DoD)

- [x] Une page de lancement avec un bouton d'accès
- [x] Un formulaire de connexion
- [x] Une page avec une liste d'élément
- [x] Une gestion de la connexion (accès sécurisé)
- [x] Une page avec les infos de l'utilisateur (username)

**Comment by Chouyoug05** [comment]
Salut est ce que tu as déjà commencé ton apprentissage ?
