### ISSUE TITLE
Retour Utilisateur Amaury

### ISSUE THREAD

**Issue by Octopus773** [Chroma-Case/Chromacase#269]
### En tant que

Dévelopeur

### Je veux

Que l'utilisateur puisse voir facilement la durée de la musique

### Estimation du temps

2 J/H

### Description

L'utilisateur ne sait pas combien de temps une musique dure et cela le perturbe

### Definition of Done (DoD)

- [x] ajout de la durée dans la db avec les différentes chansons
- [x] ajout de l'inficateur dans la songRow

**Comment by Arthi-chaud** [comment]
Closed with #282
