### ISSUE TITLE
Vérifications et purge de l'application

### ISSUE THREAD

**Issue by Arthi-chaud** [Chroma-Case/Chromacase#295]
### En tant que

Utilisateur

### Je veux

Pouvoir utiliser l'application sans bugs ou fonctionnalités non implémentée.

### Estimation du temps

9J/H

### Description

La période de développement du projet se termine. A la fin de celle-ci, l'application doit fonctionner correctement. De plus, il faut identifier et enlever tous les composants liés à des fonctionnalités qui n'ont pas été implémentés.

### Definition of Done (DoD)

- Settings
  - [x] Supprimer les options 'magic Piano' et 'piano theme' de l'onglet premium des settings
  - [x] Enlever toggle 'colorblind mode'
  - [x] enlever slider du volume du micro dans les settings
  - [x] Enlever section notifications
  - [x] Enlever la section 'global settings for the virtual piano'
- [x] Utiliser les musiques like plutot que des musiques aleatoires dans la liste de musique favorite.
- [x] Ajouter le dernier score au systeme d'include des musiques
- [x] Ajouter le meilleur score au systeme d'include des musiques
- [x] Ajouter le meilleur/dernier score aux cartes de chanson de la DiscoveryView
- [x] Coder le bouton pour ajouter une musique aux likes
- [x] Implementer les played recently
- [x] Enlever la données écrites en dur sur la DiscoveryView (cf component `GoldenRatio`)
- [x] `ScaffoldAuth`: Serve le logo de Google nous-meme
- [x] Remplacer les réferences à `https://picsum.photos/200` dans `ArtistCard`, `GenreCard` et `SearchResult` par un asset que vous providons.
- [x] Vérifier que tous les textes sont traduits
- [x] Enlever tous les ID qui sont affichés (page perso, sur la playview, ...)
- [x] DiscoveryView: Faire en sorte que le bouton like fonctionne
- APK
  - [x] Pouvoir telecharger l'APK depuis la production
  - [x] Ajouter des releases (pour recupérer l'APK)

**Comment by zoriya** [comment]
Demander un username pour les comptes guests
