### ISSUE TITLE
Gérer les requêtes lies dans le front 

### ISSUE THREAD

**Issue by zoriya** [Chroma-Case/Chromacase#300]
### En tant que

Developpeur

### Je veux

Avoir des informations liee a une resource sans faire d'autres requetes

### Estimation du temps

3 J/H

### Description

Actuellement, pour récupérer les musiques et leurs artistes, le front fait une requête pour la liste des musiques et des requêtes par musique pour récupérer leur artiste. C'est un mauvais pattern et fait N+1 requêtes a la place d'une seule ce qui est très inefficient.

### Definition of Done (DoD)

- [x] Ajouter une maniere generique de recupere les champs lies dans API.ts
- [x] Modifier chaque page front pour utiliser le nouveau système 
	- [x] Home
	- [x] Play
	- [x] Lobby
	- [x] Search
	- [x] Artist

**Comment by Arthi-chaud** [comment]
![color picker](https://media.giphy.com/media/DffShiJ47fPqM/giphy.gif?cid=ecf05e47qtqbc17cwugcg63nsehywwnr2wqxj5ongnjfkeh7&ep=v1_gifs_search&rid=giphy.gif&ct=g)
