### ISSUE TITLE
Finitions

### ISSUE THREAD

**Issue by Octopus773** [Chroma-Case/Chromacase#353]
### En tant que

Dévelopeur

### Je veux

Faire une repasse sur tous les petits éléments

### Estimation du temps

4 J/H

### Description

S'assurer qu'il n'y ait plus d'erreurs, oublis bêtes et facilement évitables

### Definition of Done (DoD)

- [x] profile with guest account overflows
- [x] Réparer le thème foncé sur mobile (transparence)
- [x] uniformiser le padding gauche/droite sur les pages
- [x] Assurer qu'aucun des textes ne soit coupé sur Android (Error des textfield, leaderboard, titre Suggestion)
- [x] Réparer la searchbar sur Android
- [x] Afficher correctement les résultats de la recherche sur Andoird

**Comment by zoriya** [comment]
Example padding:

![Screenshot_20240106-152315.png](https://github.com/Chroma-Case/Chromacase/assets/32224410/1a57d20c-4856-48fa-bf68-8e36426ed31a)

![Screenshot_20240106-152306.png](https://github.com/Chroma-Case/Chromacase/assets/32224410/cb7bea6a-2fe8-4b01-8fbd-8f47afe395f8)

**Comment by zoriya** [comment]
![image](https://github.com/Chroma-Case/Chromacase/assets/32224410/d59b5043-3e89-4de7-b11f-1e173024868e)
