### ISSUE TITLE
Google authentification

### ISSUE THREAD

**Issue by GitBluub** [Chroma-Case/Chromacase#49]
### En tant que

utilisateur

### Je veux

me connecter avec mon compte google

### Estimation du temps

4 J/H

### Description

Permettre la connexion avec un compte google depuis le front

### Definition of Done (DoD)

- [ ] Créer une application google
- [ ] Enregistrer identification google dans la base de données utilisateur
- [ ] Permettre le login via la redirection de google

**Comment by zoriya** [comment]
Marked as duplicated
