### ISSUE TITLE
Parametres Profil Utilisateur

### ISSUE THREAD

**Issue by zoriya** [Chroma-Case/Chromacase#50]
### En tant que

Developpeur

### Je veux

Terminer et reprendre la route /settings pour que l'acces à la base soit possible

### Estimation du temps

2 J/H

### Description

Stocker le profil de l'utilisateur

- prise en charge des paramètres

### Definition of Done (DoD)
- [ ] faire en sorte que id soit userId
- [ ] Créer la route POST /settings
- [ ] Créer et link les paramètres à la création du l'user (forein key)
- [ ] Tests robots framework

**Comment by AmauryDanisCousandier** [comment]
update ici aussi pour MS3
