### ISSUE TITLE
Faire le endpoint des settings

### ISSUE THREAD

**Issue by AmauryDanisCousandier** [Chroma-Case/Chromacase#60]
### En tant que

developpeur

### Je veux

envoyer des requêtes au back depuis le front pour changer un paramètre de l'app et recevoir les paramètres

### Estimation du temps

3 J/H

### Description

Faire un endpoint au niveau de l'api pour permettre au front de modifier les paramètres utilisateurs définis 

### Definition of Done (DoD)

- [ ] établir un premier jet de DbModel 
- [ ] établir une méthode GET
- [ ] établir une méthode UPDATE
- [ ] gestion d'erreur (http responses 204 404 400 500 etc)

**Comment by AnonymusRaccoon** [comment]
Je pense que l'on peut delete cette issue au profit de la #50 (quitte à augmenter le nombre de jours homme sur la #50). Tu en penses quoi @AmauryDanisCousandier ?
