### ISSUE TITLE
Amélioration de la CI

### ISSUE THREAD

**Issue by LuciferBahamut** [Chroma-Case/Chromacase#67]
### En tant que

Développeur

### Je veux

Vérifier que mon travail est toujours fonctionnel

### Estimation du temps

8J/H

### Description

Amélioration de la CI existante pour tester plus de cas de figures et s'assurer du bon fonctionnement du programme à chaque modification

### Definition of Done (DoD)
- [x] Corriger les tests unitaires du back
- [x] Ajouter des conditions entre les différents jobs
- [x] Mettre un temps limite au jobs de la CI
- [x] Afficher le résultat des tests unitaires dans le job summary
- [x] Afficher le résultat des tests unitaires dans les pull request
- [x] Ajouter différent trigger pour le déploiement

**Comment by AmauryDanisCousandier** [comment]
le reste de la ci front étant indépendante, j'ai move le reste de la tache sur une issue séparée
