### ISSUE TITLE
Créer un système de recherche

### ISSUE THREAD

**Issue by zoriya** [Chroma-Case/Chromacase#71]
### En tant que

Utilisateur

### Je veux

Pouvoir rechercher une musique, un album,  un artiste

### Estimation du temps

6 J/H

### Description

créer une route search qui permet de récupérer les informations d'un morceau, d'un album, d'un artiste, selon de critères differents

### Definition of Done (DoD)
- [x] lire la doc Prisma
- [x] recherche de sons, par nom, artiste, album et genre
- [x] recherche d'artists par nom
- [x] recherche d'album par nom et par artiste
- [x] recherche par mots clef et titres partiels
    - [x] pour les sons
    - [x] pour les albums
    - [x] pour les artistes
- [ ] réaliser les tests robot

**Comment by AmauryDanisCousandier** [comment]
j'ai update la tâche en virant elasticSearch :)
